### ISSUE TITLE
about ELF_MAGICK ELF_ENCRYPTED_MAGICK

### ISSUE THREAD

**Issue by GUANCAIBAN** [doubleword/ctfwriteups#1]
hi,doubleword.
I wonder know why you use elf magick to brute and where did you find ELF_ENCRYPTED_MAGICK?
Thanks.

**Comment by doubleword** [comment]
ELF_ENCRYPTED_MAGICK are the first four bytes of encryptedBytes. Since encryptedBytes is actually an encrypted ELF file, the first four bytes are an encrypted ELF magic (https://en.wikipedia.org/wiki/Executable_and_Linkable_Format). I updated the writeup. It should be more clear now (https://github.com/doubleword/ctfwriteups/blob/main/VolgaCTF2022Qualifier/future/writeup.md#:~:text=encryptedBytes%20is%20an,the%20correct%20seed.).

**Comment by pkukmkk** [comment]
ELF_ENCRYPTED_MAGICK are the first four bytes of encryptedBytes. Since encryptedBytes is actually an encrypted ELF file, the first four bytes are an encrypted ELF magic (https://en.wikipedia.org/wiki/Executable_and_Linkable_Format). I updated the writeup. It should be more clear now.

**Comment by GUANCAIBAN** [comment]
Oh,yeah.Thanks for your reply.

**Comment by pkukmkk** [comment]
ELF_ENCRYPTED_MAGICK are the first four bytes of encryptedBytes. Since
encryptedBytes is actually an encrypted ELF file, the first four bytes are
an encrypted ELF magic (
https://en.wikipedia.org/wiki/Executable_and_Linkable_Format). I updated
the writeup. It should be more clear now (
https://github.com/doubleword/ctfwriteups/blob/main/VolgaCTF2022Qualifier/future/writeup.md#:~:text=encryptedBytes%20is%20an,the%20correct%20seed.
).

чт, 19 мая 2022 г. в 12:49, GUANCAIBAN ***@***.***>:
